FROM nginx:alpine

RUN mkdir -p /etc/ssl/private /etc/ssl/certs

COPY ssl/ /etc/ssl/
COPY html/ /usr/share/nginx/html/
COPY css/ /usr/share/nginx/html/css/
COPY js/ /usr/share/nginx/html/js/
COPY assets/ /usr/share/nginx/html/assets/
COPY nginx-prod.conf /etc/nginx/nginx.conf

EXPOSE 443

CMD ["nginx", "-g", "daemon off;"]
