FROM nginx:alpine

RUN mkdir -p /etc/ssl/private /etc/ssl/certs

COPY ssl/ /etc/ssl/
COPY index.html /usr/share/nginx/html/index.html
COPY html/ /usr/share/nginx/html/html/
COPY css/ /usr/share/nginx/html/css/
COPY js/ /usr/share/nginx/html/js/
COPY assets/ /usr/share/nginx/html/assets/
COPY templates/ /usr/share/nginx/html/templates/
COPY nginx-prod.conf /etc/nginx/nginx.conf

EXPOSE 80 443

CMD ["nginx", "-g", "daemon off;"]
