[project]
name = "nexus_inventory_backend"
version = "1.0.0"
requires-python = ">=3.13"
dependencies = [
    "django>=6.0",
    "django-configurations",
    "django-extensions",
    "djangorestframework",
    "drf-spectacular",
    "drf-spectacular[sidecar]",
    "sentry-sdk[django]",
    "django-environ",
    "djangorestframework-simplejwt",
    "django-filter",
    "drf-nested-routers",
    "django-cors-headers",
]

[project.optional-dependencies]
test = [
    "pytest",
    "pytest-django",
    "pytest-cov"
]

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "nexus_inventory_backend.settings"
python_files = [
    "test_*.py",
    "*_test.py"
]
